### PR TITLE
Update for TYPO3 7 LTS

### PR DESCRIPTION
**Pull request by cedricziel**
Feel free to jump in :)

### CODE REVIEW

**Comment by bjo3rnf** [comment]
Oh, thanks! Are you actually using this?

**Comment by cedricziel** [comment]
I'm in need for something like it - and I remembered yours :)

I'l look try to finish it today.

**Comment by cedricziel** [comment]
Alright. finished :)

Works flawlessly. Thanks a bunch for opensourcing it!

**Comment by cedricziel** [comment]
Took it to production yesterday.

**Comment by bjo3rnf** [comment]
Awesome! I was about to ask about namespaces. Thanks a bunch!

**Comment by cedricziel** [comment]
aww-sum! :-)

You're welcome - thank you for crafting it initially.

**Pull request merged**
